"""create players and matches

Revision ID: 7232fa0f199c
Revises: 
Create Date: 2026-08-11 18:14:40.725378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7232fa0f199c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_qr_code'), 'players', ['qr_code'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerOne_id', sa.Integer(), nullable=False),
    sa.Column('playerTwo_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('playerOne_score', sa.Integer(), nullable=True),
    sa.Column('playerTwo_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['playerOne_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['playerTwo_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_playerOne_id'), 'matches', ['playerOne_id'], unique=False)
    op.create_index(op.f('ix_matches_playerTwo_id'), 'matches', ['playerTwo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_playerTwo_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_playerOne_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_players_qr_code'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
